apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Infrastructure components
  sourceRepos:
    - https://kubernetes.github.io/ingress-nginx
    - https://kubernetes-sigs.github.io/metrics-server/
    - https://github.com/minhtri1612/learning_RKE2.git
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
