apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging
  namespace: argocd
spec:
  description: Staging Environment Project
  sourceRepos:
  - 'https://github.com/minhtri1612/learning_RKE2.git'
  destinations:
  - namespace: 'meo-stationery'
    server: '*'
  - namespace: 'database'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
