# ArgoCD AppProject for Production
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
spec:
  description: Production environment applications
  
  sourceRepos:
    - 'https://github.com/minhtri1612/learning_RKE2.git'
    - 'https://github.com/minhtri1612/practice_RKE2.git'
  
  destinations:
    - namespace: 'meo-stationery'
      server: '*'
    - namespace: 'database'
      server: '*'
    - namespace: 'external-secrets'
      server: '*'
  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
