sourceRepos:
  - https://github.com/minhtri1612/learning_RKE2.git
  - https://prometheus-community.github.io/helm-charts
  - https://helm.cilium.io/

defaultServer: https://kubernetes.default.svc

environments:
  - name: dev
    cluster: dev
    namespaces:
      - meo-stationery
      - database
      - monitoring
      - kube-system
      - cilium-secrets
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: "*"
        kind: "*"
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"

  - name: staging
    cluster: staging
    namespaces:
      - meo-stationery
      - database
      - monitoring
      - kube-system
      - cilium-secrets
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: "*"
        kind: "*"
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"

  - name: prod
    cluster: prod
    namespaces:
      - meo-stationery
      - database
      - monitoring
      - kube-system
      - cilium-secrets
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: "storage.k8s.io"
        kind: StorageClass
      - group: "apiextensions.k8s.io"
        kind: CustomResourceDefinition
      - group: "rbac.authorization.k8s.io"
        kind: ClusterRole
      - group: "rbac.authorization.k8s.io"
        kind: ClusterRoleBinding
      - group: "admissionregistration.k8s.io"
        kind: ValidatingWebhookConfiguration
      - group: "admissionregistration.k8s.io"
        kind: MutatingWebhookConfiguration
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"