repoURL: https://github.com/minhtri1612/learning_RKE2.git
defaultServer: https://kubernetes.default.svc

environments:
  - name: dev
    cluster: dev
    namespaces:
      - meo-stationery
      - database
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"          # dev: thoải mái, dễ debug

  - name: staging
    cluster: staging
    namespaces:
      - meo-stationery
      - database
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"

  - name: prod
    cluster: prod
    namespaces:
      - meo-stationery
      - database
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: "storage.k8s.io"
        kind: StorageClass
    namespaceResourceWhitelist:
      - group: "argoproj.io"
        kind: Application
      - group: ""
        kind: ServiceAccount
      - group: "apps"
        kind: Deployment
      - group: "apps"
        kind: StatefulSet
      - group: ""
        kind: Service
      - group: ""
        kind: ConfigMap
      - group: ""
        kind: Secret
      - group: ""
        kind: PersistentVolumeClaim
      - group: "networking.k8s.io"
        kind: Ingress
      - group: "networking.k8s.io"
        kind: NetworkPolicy
      - group: "autoscaling"
        kind: HorizontalPodAutoscaler
      - group: "policy"
        kind: PodDisruptionBudget
      - group: "batch"
        kind: Job