{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "generic-app.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    {{- with .Values.argocd }}
    argocd.argoproj.io/sync-wave: {{ .syncWave | default "0" | quote }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.platform_network.enable_tls }}
  tls:
  - hosts:
    - {{ printf "%s.%s" .Values.app_name .Values.platform_network.base_domain | quote }}
    secretName: {{ printf "%s-tls" .Values.app_name }}
  {{- end }}
  rules:
  - host: {{ printf "%s.%s" .Values.app_name .Values.platform_network.base_domain | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "generic-app.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
