meostation:
  name: prod-meostation-stack
  project: prod
  repoURL: https://github.com/minhtri1612/learning_RKE2.git
  targetRevision: v1.2.3
  path: k8s_helm/meo-station
  valueFiles:
    - values.yaml
    - values-prod.yaml

infrastructure:
  enabled: true
  project: infrastructure
  destinationName: prod
  ingress:
    name: prod-ingress-nginx
    targetRevision: 4.8.3
    helmValues: |
      controller:
        admissionWebhooks:
          enabled: false
        service:
          type: NodePort
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        metrics:
          enabled: true
          serviceMonitor:
            enabled: false
        podDisruptionBudget:
          enabled: true
          minAvailable: 2
  metrics:
    name: prod-metrics-server
    targetRevision: 3.12.0
    helmValues: |
      args:
        - --kubelet-insecure-tls
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
  externalsecrets:
    name: externalsecrets-prod
    repoURL: https://github.com/minhtri1612/learning_RKE2.git
    targetRevision: v1.2.3
    valueFiles:
      - values.yaml
      - values-prod.yaml
