meostation:
  name: dev-meostation-stack
  project: dev
  repoURL: https://github.com/minhtri1612/learning_RKE2.git
  targetRevision: main
  path: k8s_helm/meo-station
  valueFiles:
    - values.yaml
    - values-dev.yaml

infrastructure:
  enabled: true
  project: infrastructure
  destinationName: dev
  ingress:
    name: dev-ingress-nginx
    targetRevision: 4.8.3
    helmValues: |
      controller:
        admissionWebhooks:
          enabled: false
        service:
          type: NodePort
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        metrics:
          enabled: true
          serviceMonitor:
            enabled: false
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
  metrics:
    name: dev-metrics-server
    targetRevision: 3.12.0
    helmValues: |
      args:
        - --kubelet-insecure-tls
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
  externalsecrets:
    name: externalsecrets-dev
    repoURL: https://github.com/minhtri1612/learning_RKE2.git
    targetRevision: main
    valueFiles:
      - values.yaml
      - values-dev.yaml
