replicaCount: 3

ingress:
  host: meo-stationery-dev.local

databaseConnection:
  host: dev-meostation-database-app-generic-app.database.svc.cluster.local

migration:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5

existingSecret:
  name: meo-stationery-backend-secrets-dev
