# Dev overrides (merged with values.yaml)
existingSecret:
  name: "meo-stationery-backend-secrets-dev"   # từ ExternalSecret dev (target.name trong externalsecret-backend.yaml)
replicaCount: 3
workload:
  image: minhtri1612/meo-stationery-backend:vcl
  resources:
    requests:
      memory: "128Mi"
      cpu: "64m"
    limits:
      memory: "512Mi"
      cpu: "500m"
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
ingress:
  host: meo-stationery-dev.local
