replicaCount: 3

ingress:
  host: meo-stationery-dev.local

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5

migration:
  enabled: false

existingSecret:
  name: meo-stationery-backend-secrets-dev
