{{- range $appName, $appConfigFull := .Values }}
{{- if typeIs "map[string]interface {}" $appConfigFull }}
{{- $appConfig := $appConfigFull.secrets }}
{{- if and $appConfig $appConfig.data (gt (len $appConfig.data) 0) }}
{{- $target := index $appConfig "target" | default dict }}
{{- $hasTargetName := and $target $target.name }}
{{- $esName := "" }}
{{- if $hasTargetName }}
{{- $esName = $target.name }}
{{- else }}
{{- $esName = printf "%s%s" (printf "%s-%s-secrets" $.Values.projectName $appName) (include "external-secrets.k8sSecretSuffix" $) }}
{{- end }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $esName }}
  namespace: {{ $appConfigFull.namespace | default "default" }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $appConfigFull.syncWave | default "-2" | quote }}
spec:
  refreshInterval: {{ $appConfig.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ $.Values.secretStoreName | default "aws-secrets-manager" }}
    kind: ClusterSecretStore
  target:
    name: {{ $esName }}
    creationPolicy: Owner
  data:
    {{- range $item := $appConfig.data }}
    - secretKey: {{ $item.secretKey }}
      remoteRef:
        key: {{ $item.remoteRef.key | default $appConfig.remoteKey | default $.Values.awsSecretKey }}
        property: {{ $item.remoteRef.property }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
