# Prod: override cho umbrella (backend + database subcharts), pin version tại Application
env: prod
project: prod
destination: prod

backend:
  namespace: meo-stationery
  existingSecret:
    name: "meo-stationery-backend-secrets"
  replicaCount: 2
  workload:
    image: minhtri1612/meo-stationery-backend:vcl
    resources:
      requests:
        memory: "256Mi"
        cpu: "128m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
  ingress:
    host: meo-stationery.local
  networkPolicy:
    enabled: true

database:
  namespace: database
  existingSecret:
    name: "meo-stationery-database-secrets"
  auth:
    username: meo_admin
    database: meo_stationery
    password: ""
  persistence:
    useEBS: false
  replicas: 1
