apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-secrets-prod
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: postgres
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: meo-stationery/prod/app-credentials
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: meo-stationery/prod/app-credentials
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: meo-stationery/prod/app-credentials
        property: POSTGRES_DB
