apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  # Examples of params:
  # server.insecure: "true"
  # reposerver.timeout.seconds: "60"
  controller.status.processors: "20"
