apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      # Generator 1: List of apps
      - list:
          elements:
          - app: backend
            path: k8s_helm/backend
            namespace: meo-stationery
          - app: database
            path: k8s_helm/database
            namespace: database
      # Generator 2: List of environments
      - list:
          elements:
          - env: dev
            project: dev
            server: https://10.1.101.198:6443
            branch: dev
            prune: "true"
          - env: prod
            project: prod
            server: https://10.2.101.11:6443
            branch: main
            prune: "false"
  template:
    metadata:
      name: 'meo-station-{{app}}-{{env}}'
      namespace: argocd
    spec:
      project: '{{project}}'
      source:
        repoURL: https://github.com/minhtri1612/learning_RKE2.git
        targetRevision: '{{branch}}'
        path: '{{path}}'
        helm:
          valueFiles:
          - values.yaml
          - values-{{env}}.yaml
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: '{{prune}}'
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
