apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications-dev
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/minhtri1612/learning_RKE2.git
      revision: dev
      files:
      - path: "k8s_helm/*/config.json"
  template:
    metadata:
      name: 'meo-station-{{path.basename}}-dev'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
    spec:
      project: dev
      source:
        repoURL: https://github.com/minhtri1612/learning_RKE2.git
        targetRevision: '{{version}}'
        path: '{{helmPath}}'
        helm:
          valueFiles:
          - values.yaml
          - values-dev.yaml
      destination:
        name: dev
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
      - group: apps
        kind: StatefulSet
        jsonPointers:
        - /spec/replicas
      - group: autoscaling
        kind: HorizontalPodAutoscaler
        jsonPointers:
        - /status
        - /metadata/annotations
      - group: ""
        kind: Secret
        jsonPointers:
        - /data
      - group: ""
        kind: Service
        jsonPointers:
        - /metadata/annotations
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications-prod
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/minhtri1612/learning_RKE2.git
      revision: main
      files:
      - path: "k8s_helm/*/config.json"
  template:
    metadata:
      name: 'meo-station-{{path.basename}}-prod'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
    spec:
      project: prod
      source:
        repoURL: https://github.com/minhtri1612/learning_RKE2.git
        targetRevision: '{{version}}'
        path: '{{helmPath}}'
        helm:
          valueFiles:
          - values.yaml
          - values-prod.yaml
      destination:
        name: prod
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
      - group: apps
        kind: StatefulSet
        jsonPointers:
        - /spec/replicas
      - group: autoscaling
        kind: HorizontalPodAutoscaler
        jsonPointers:
        - /status
        - /metadata/annotations
