apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater-controller
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.9.1
    helm:
      values: |
        config:
          registries:
            - name: Docker Hub
              prefix: docker.io
              api_url: https://index.docker.io/v1
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
