{{- if not .Values.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.database.auth.username }}:{{ .Values.database.auth.password | default "" }}@{{ .Values.database.fullnameOverride }}.{{ .Values.database.namespace | default .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.database.auth.database }}?schema=public"
  NEXTAUTH_SECRET: {{ .Values.secret.nextAuthSecret | quote }}
{{- end }}