{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backend.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.argocd }}
    argocd.argoproj.io/sync-wave: {{ .syncWave | default "0" | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if hasKey .Values.serviceAccount "automount" }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
  {{- end }}
{{- end }}
