apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kind-staging-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.18.255.20-172.18.255.29
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-staging
  namespace: metallb-system
spec:
  ipAddressPools:
    - kind-staging-pool
