env: prod

projectName: meo-stationery
awsBackendSecretKey: meo-stationery/prod/app-credentials
awsDatabaseSecretKey: /meo-stationery/prod/database

backend:
  refreshInterval: 1h
database:
  refreshInterval: 1h
