repoURL: https://github.com/minhtri1612/learning_RKE2.git
name: meostation
env: ""
project: ""
cluster: ""
automated: false

appsByEnv:
  dev:
    backend:
      namespace: meo-stationery
      syncWave: "1"
    database:
      namespace: database
      syncWave: "0"
    frontend:
      namespace: meo-stationery
      syncWave: "2"
  prod:
    backend:
      namespace: meo-stationery
      syncWave: "1"
    database:
      namespace: database
      syncWave: "0"
    redis:
      namespace: meo-stationery
      syncWave: "1"
  staging:
    backend:
      namespace: meo-stationery
      syncWave: "1"
    database:
      namespace: database
      syncWave: "0"
