nameOverride: "postgres"
fullnameOverride: "postgres"

argocd:
  syncWave: "0"

namespace: ""

image:
  repository: postgres
  pullPolicy: Always
  tag: "13"

service:
  type: ClusterIP
  port: 5432

serviceAccount:
  create: false

auth:
  username: "meo_admin"
  database: "meo_stationery"
  password: ""

existingSecret:
  name: ""

replicas: 0

persistence:
  size: 1Gi
  storageClassName: ""
  useEBS: true
  provisionStorageClass: false

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
