existingSecret:
  name: "meo-stationery-database-secrets"
auth:
  username: meo_admin
  database: meo_stationery
  password: ""
persistence:
  size: 10Gi
  useEBS: false
  provisionStorageClass: false

replicas: 1
