# Đồng bộ AWS secret app-credentials (dev) → K8s Secret postgres (namespace database).
# Helm database chart dùng existingSecret.name: "postgres".
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-secrets-dev
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: postgres
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: meo-stationery/dev/app-credentials-v2
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: meo-stationery/dev/app-credentials-v2
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: meo-stationery/dev/app-credentials-v2
        property: POSTGRES_DB
