---
# Source: template/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-backend
  labels:
    helm.sh/chart: template-0.1.0
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: prod-backend
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: template/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prod-backend
  labels:
    helm.sh/chart: template-0.1.0
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: prod-backend
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: prod-backend
---
# Source: template/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-backend
  labels:
    helm.sh/chart: template-0.1.0
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: prod-backend
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  
  replicas: 8
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app.kubernetes.io/instance: prod-backend
  template:
    metadata:
      labels:
        helm.sh/chart: template-0.1.0
        app.kubernetes.io/name: backend
        app.kubernetes.io/instance: prod-backend
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: prod-backend
      containers:
        - name: template
          image: "minhtri1612/rke2:3.0.1"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 128m
              memory: 256Mi
---
# Source: template/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "prod-backend-test-connection"
  labels:
    helm.sh/chart: template-0.1.0
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: prod-backend
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['prod-backend:80']
  restartPolicy: Never
