# ClusterSecretStore: ESO dùng AWS credentials từ K8s Secret để đọc Secrets Manager.
# Trước khi apply: tạo secret aws-secrets-credentials trong namespace external-secrets
# (xem README trong external-secrets/).
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secrets-credentials
            namespace: external-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: aws-secrets-credentials
            namespace: external-secrets
            key: secret-access-key
