env: staging
projectName: meo-stationery

# Source của secrets cho External Secret Engine
secrets:
  backend:
    remoteKey: meo-stationery/staging/app-credentials
    refreshInterval: 1h
  database:
    remoteKey: meo-stationery/staging/app-credentials
    refreshInterval: 1h
