apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-app.fullname" . }}-configmap
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
data:
  NEXTAUTH_URL: {{ .Values.config.nextAuthUrl | quote }}
  NODE_ENV: "production"
