{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "generic-app.fullname" . }}-pdb
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
  {{- with .Values.argocd }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave | default "0" | quote }}
  {{- end }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "generic-app.selectorLabels" . | nindent 6 }}
{{- end }}
