# ─── LAYER 2 – PLATFORM ───
# Chỉ platform config. App base = app-base.yaml, env override = environments/*.yaml.

repoURL: https://github.com/minhtri1612/learning_RKE2.git
name: meostation      # project name — dùng trong <env>-<name>-<service>-app

env: ""
project: ""
cluster: ""
automated: false
