{{- range $name, $app := .Values.apps }}
{{- $svc := index $.Values.services $name | default dict }}
{{- $targetRev := $svc.version | default $app.targetRevision }}
{{- $svcValues := omit $svc "version" }}
{{- $mergedValues := merge $app.values $svcValues }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.env }}-{{ $app.name }}-stack
  namespace: argocd
  labels:
    env: {{ $.Values.env }}
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: {{ $targetRev }}
    path: {{ $app.path }}
    helm:
      values: |
        {{ toYaml $mergedValues | nindent 8 }}
  destination:
    name: {{ $.Values.cluster }}
    namespace: {{ $app.namespace }}
  syncPolicy:
    {{- if $.Values.automated }}
    automated:
      prune: true
      selfHeal: true
    {{- end }}
    syncOptions:
      - CreateNamespace=true
---
{{- end }}
