apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.env }}-backend-stack
  namespace: argocd
  labels:
    env: {{ .Values.env }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.backend.targetRevision }}
    path: k8s_helm/backend
    helm:
      values: |
        {{ toYaml .Values.backend.values | nindent 8 }}
  destination:
    name: {{ .Values.cluster }}
    namespace: meo-stationery
  syncPolicy:
    {{- if .Values.automated }}
    automated:
      prune: true
      selfHeal: true
    {{- end }}
    syncOptions:
      - CreateNamespace=true
