# PROD override — chỉ phần khác so với config/base/config.yaml

backend:
  secrets:
    target:
      name: meo-stationery-backend-secrets-prod
    remoteKey: meo-stationery/prod/app-credentials

database:
  secrets:
    target:
      name: meo-stationery-database-secrets-prod
    remoteKey: meo-stationery/prod/app-credentials

