runtimeConfig:
  enabled: true
  fileName: app.yaml
  mountPath: /app/config
  data:
    app:
      env: staging
      logLevel: info
      httpPort: 3000
    database:
      host: postgres.database.svc.cluster.local
      port: 5432
      name: meo_stationery
      ssl: false
    cache:
      enabled: true
      host: redis.default.svc.cluster.local
      port: 6379
    featureFlags:
      enableMetrics: true
