apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-app-dev
  namespace: argocd
  labels:
    env: dev
spec:
  project: dev
  source:
    repoURL: https://github.com/minhtri1612/learning_RKE2.git
    targetRevision: kind
    path: k8s_helm/database
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    name: dev
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
