apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-app-prod
  namespace: argocd
  labels:
    env: prod
spec:
  project: prod
  source:
    repoURL: https://github.com/minhtri1612/learning_RKE2.git
    targetRevision: kind
    path: k8s_helm/database
    helm:
      valueFiles:
        - values.yaml
        - ../../argocd/env-values/prod/database-values.yaml
  destination:
    name: prod
    namespace: database
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

