apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to base Helm chart
helmCharts:
  - name: applications
    releaseName: argocd-apps-dev
    namespace: argocd
    repo: ../../base
    valuesFile: values.yaml
