env: dev

defaults:
  targetRevision: dev    # Dev sync từ branch dev

apps:
  backend:
    enabled: true
    project: dev    # Thuộc project dev
    path: k8s_helm/backend
    namespace: meo-stationery
    destination:
      server: __CLUSTER_SERVER_DEV__
    ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas

  database:
    enabled: true
    project: dev    # Thuộc project dev
    path: k8s_helm/database
    namespace: database
    destination:
      server: __CLUSTER_SERVER_DEV__
    ignoreDifferences:
      - group: apps
        kind: StatefulSet
        jsonPointers:
        - /spec/volumeClaimTemplates
        - /spec/serviceName
