{{- if and .Values.rollout.enabled .Values.rollout.analysis.enabled (ne (.Values.workloadKind | default "deployment") "statefulset") }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "template.rolloutAnalysisTemplateName" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
spec:
  metrics:
    - name: success-rate
      interval: {{ .Values.rollout.analysis.prometheus.interval | default "1m" }}
      count: {{ .Values.rollout.analysis.prometheus.count | default 3 }}
      failureLimit: {{ .Values.rollout.analysis.prometheus.failureLimit | default 1 }}
      successCondition: {{ .Values.rollout.analysis.prometheus.successCondition | default "result[0] >= 0.95" | quote }}
      provider:
        prometheus:
          address: {{ .Values.rollout.analysis.prometheus.address | quote }}
          query: |
            {{- .Values.rollout.analysis.prometheus.query | nindent 12 }}
{{- end }}
{{- if and (ne (.Values.workloadKind | default "deployment") "statefulset") .Values.rollout.enabled .Values.rollout.analysis.enabled }}
{{- range $tpl := .Values.rollout.analysis.templates }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ $tpl.name }}
  labels:
    {{- include "template.labels" $ | nindent 4 }}
spec:
  {{- with $tpl.args }}
  args:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  metrics:
    {{- toYaml $tpl.metrics | nindent 4 }}
---
{{- end }}
{{- end }}
{{- if and (ne (.Values.workloadKind | default "deployment") "statefulset") .Values.rollout.enabled .Values.rollout.analysis.enabled }}
{{- range $tpl := .Values.rollout.analysis.templates }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ $tpl.name }}
  labels:
    {{- include "template.labels" $ | nindent 4 }}
spec:
  {{- with $tpl.args }}
  args:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  metrics:
    {{- toYaml $tpl.metrics | nindent 4 }}
---
{{- end }}
{{- end }}
{{- if and (ne (.Values.workloadKind | default "deployment") "statefulset") .Values.rollout.enabled .Values.rollout.analysis.enabled }}
{{- range $tpl := .Values.rollout.analysis.templates }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ $tpl.name }}
  labels:
    {{- include "template.labels" $ | nindent 4 }}
spec:
  {{- with $tpl.args }}
  args:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  metrics:
    {{- toYaml $tpl.metrics | nindent 4 }}
---
{{- end }}
{{- end }}
{{- if and (ne (.Values.workloadKind | default "deployment") "statefulset") .Values.rollout.analysis.enabled }}
{{- range $tpl := .Values.rollout.analysis.templates }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ $tpl.name }}
  labels:
    {{- include "template.labels" $ | nindent 4 }}
spec:
  {{- with $tpl.args }}
  args:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  metrics:
    {{- toYaml $tpl.metrics | nindent 4 }}
---
{{- end }}
{{- end }}
