{{- if ne (.Values.workloadKind | default "deployment") "statefulset" }}
{{- $svcName := .Values.currentService | default "backend" }}
{{- $svc := (index .Values $svcName) | default dict }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "template.fullname" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
spec:
  replicas: {{ $svc.replicaCount | default .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.rollout.revisionHistoryLimit | default 3 }}
  selector:
    matchLabels:
      {{- include "template.selectorLabels" . | nindent 6 }}
  strategy:
    canary:
      stableService: {{ .Values.rollout.canary.stableService | default (printf "%s-stable" (include "template.fullname" .)) }}
      canaryService: {{ .Values.rollout.canary.canaryService | default (printf "%s-canary" (include "template.fullname" .)) }}
      {{- with .Values.rollout.canary.maxSurge }}
      maxSurge: {{ . }}
      {{- end }}
      {{- with .Values.rollout.canary.maxUnavailable }}
      maxUnavailable: {{ . }}
      {{- end }}
      steps:
        {{- toYaml .Values.rollout.canary.steps | nindent 8 }}
  template:
    {{- include "template.workloadPodSpec" . | nindent 4 }}
{{- end }}
