apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externalsecrets-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: dev
  source:
    repoURL: https://github.com/minhtri1612/learning_RKE2.git
    targetRevision: main
    path: argocd/externalsecrets
    directory:
      recurse: true
  destination:
    name: dev
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

