# Default values for applications.
# This is a YAML-formatted file.

defaults:
  project: default
  repoURL: https://github.com/minhtri1612/learning_RKE2.git
  targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true

# Applications to deploy
# apps:
#   backend:
#     enabled: true
#     path: k8s_helm/backend
#     namespace: meo-stationery
#     ignoreDifferences: [] 
#     destination:
#       server: https://kubernetes.default.svc
#     helm:
#       valueFiles:
#         - values.yaml
