apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.meostation.name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: {{ .Values.meostation.project }}
  source:
    repoURL: {{ .Values.meostation.repoURL }}
    targetRevision: {{ .Values.meostation.targetRevision }}
    path: {{ .Values.meostation.path }}
    helm:
      valueFiles: {{ .Values.meostation.valueFiles | toJson }}
  destination:
    server: {{ .Values.meostation.server | default "https://kubernetes.default.svc" }}
    namespace: argocd
  syncPolicy:
{{- if .Values.meostation.syncPolicy }}
{{ toYaml .Values.meostation.syncPolicy | indent 4 }}
{{- end }}
