#!/usr/bin/env bash
# Create ArgoCD cluster secrets from kubeconfig files
# This allows ArgoCD to manage dev/prod clusters

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MGMT_KUBECONFIG="$ROOT_DIR/kube_config_rke2_management.yaml"

cd "$ROOT_DIR"

if [[ ! -f "$MGMT_KUBECONFIG" ]]; then
  echo "Error: Management kubeconfig not found: $MGMT_KUBECONFIG"
  exit 1
fi

export KUBECONFIG="$MGMT_KUBECONFIG"

create_cluster_secret() {
  local env="$1"
  # Use standard kubeconfig generated by deploy.py (already has private IP)
  local kubeconfig_file="$ROOT_DIR/kube_config_rke2_${env}.yaml"
  
  if [[ ! -f "$kubeconfig_file" ]]; then
    # Fallback to _private version if standard doesn't exist
    if [[ -f "$ROOT_DIR/kube_config_rke2_${env}_private.yaml" ]]; then
      kubeconfig_file="$ROOT_DIR/kube_config_rke2_${env}_private.yaml"
    else
      echo "  ⚠ Skipping $env: kubeconfig not found at $kubeconfig_file"
      return 0
    fi
  fi
  
  echo "Processing $env cluster..."
  
  # Extract cluster info from kubeconfig
  local server=$(yq eval '.clusters[0].cluster.server' "$kubeconfig_file")
  local client_cert=$(yq eval '.users[0].user.client-certificate-data' "$kubeconfig_file")
  local client_key=$(yq eval '.users[0].user.client-key-data' "$kubeconfig_file")
  
  if [[ -z "$server" || "$server" == "null" ]]; then
    echo "  ✗ Failed to extract server URL from kubeconfig"
    return 1
  fi
  
  echo "  Server: $server"
  
  # Create ArgoCD cluster secret with insecure mode (skip TLS verification)
  # This is acceptable for private VPC peering communication
  kubectl create secret generic "cluster-${env}" \
    --namespace=argocd \
    --from-literal=name="${env}" \
    --from-literal=server="${server}" \
    --from-literal=config='{"tlsClientConfig":{"insecure":true,"certData":"'"${client_cert}"'","keyData":"'"${client_key}"'"}}' \
    --dry-run=client -o yaml | \
    kubectl label -f - argocd.argoproj.io/secret-type=cluster --local --dry-run=client -o yaml | \
    kubectl apply -f -
  
  echo "  ✓ Cluster secret created for $env"

  # Also update the manifest file in Git so ArgoCD syncs correct credentials
  local manifest_file="$ROOT_DIR/argocd/clusters/cluster-${env}.yaml"
  if [[ -f "$manifest_file" ]]; then
    yq eval ".stringData.server = \"${server}\"" -i "$manifest_file"
    # Write config JSON using Python to avoid yq quoting issues with JSON values
    python3 - "$manifest_file" "$client_cert" "$client_key" <<'PYEOF'
import sys, json, re
manifest_path, cert, key = sys.argv[1], sys.argv[2], sys.argv[3]
config = json.dumps({"tlsClientConfig": {"insecure": True, "certData": cert, "keyData": key}})
with open(manifest_path, 'r') as f:
    content = f.read()
# Replace entire config value (single-line or leftover multi-line) to avoid broken YAML
if 'config:' in content:
    content = re.sub(r"(\s+config:).*", f"\\1 '{config}'\n", content, count=1, flags=re.DOTALL)
else:
    content = content.rstrip('\n') + f"\n  config: '{config}'\n"
with open(manifest_path, 'w') as f:
    f.write(content)
PYEOF
    echo "  ✓ Updated manifest file (with creds): argocd/clusters/cluster-${env}.yaml"
  fi
}

echo "Creating ArgoCD cluster secrets..."
echo ""

# If an argument is provided, only process that environment
ENVS_TO_PROCESS="dev prod"
if [[ -n "$1" ]]; then
  ENVS_TO_PROCESS="$1"
fi

for env in $ENVS_TO_PROCESS; do
  create_cluster_secret "$env"
  echo ""
done

echo "Done! Verifying clusters..."
kubectl get secret -n argocd -l argocd.argoproj.io/secret-type=cluster -o custom-columns=NAME:.metadata.name,SERVER:.data.server | while read name server; do
  if [[ -n "$server" && "$server" != "SERVER" ]]; then
    decoded=$(echo "$server" | base64 -d 2>/dev/null || echo "")
    echo "  - $name: $decoded"
  fi
done

echo ""
echo "Clusters registered! ArgoCD applications should start syncing now."
echo "Check status: kubectl get applications -n argocd"
