replicaCount: 3

ingress:
  host: meo-stationery-dev.local

databaseConnection:
  host: dev-database-generic-app.database.svc.cluster.local

autoscaling:
  minReplicas: 3
  maxReplicas: 5

existingSecret:
  name: meo-stationery-backend-secrets-dev
