apiVersion: v1
kind: Secret
metadata:
  name: repo-learning-rke2
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: https://github.com/minhtri1612/learning_RKE2.git
  # username: <git-user>
  # password: <git-token>
