apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app-dev
  namespace: argocd
  labels:
    env: dev
spec:
  project: dev
  source:
    repoURL: https://github.com/minhtri1612/learning_RKE2.git
    targetRevision: kind
    path: k8s_helm/backend
    helm:
      valueFiles:
        - values.yaml
        - ../../argocd/env-values/dev/backend-values.yaml
  destination:
    name: dev
    namespace: meo-stationery
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
