# PARENT: Apply này → tự đẻ ra backend-app-dev, backend-app-prod
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minhtri1612/learning_RKE2.git
    targetRevision: kind
    path: argocd/stacks/backend-app
    directory:
      recurse: false
      exclude: 'backend-app.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
