# Minimal values for workload clusters (Spokes)
# These only provide metrics to the management cluster

grafana:
  enabled: false

prometheus:
  enabled: false # We don't need a local Prometheus server on the workload clusters

alertmanager:
  enabled: false

prometheusOperator:
  enabled: true # We need the operator to manage the node-exporter and kube-state-metrics

nodeExporter:
  enabled: true
  service:
    type: ClusterIP # We don't need an external IP, as our mgmt Prometheus scrapes directly via Node IP/Port

kubeStateMetrics:
  enabled: true
  service:
    type: NodePort
    nodePort: 30080

# Disable system components to avoid 'kube-system' namespace permission issues in Kind
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
