# Tag/replica + env. useExternalSecrets mặc định true trong template/values.yaml.
# helm ... -f app/be.yaml|db.yaml -f env/prod.yaml

env: prod

backend:
  image:
    tag: "4.0.1"
  replicaCount: 7
  rollout:
    enabled: true
    strategy: canary
database:
  image:
    tag: "16"
  replicaCount: 2
