# Chỉ tag phiên bản image — team developer.
# helm ... -f app/be.yaml|db.yaml -f env/prod.yaml

backend:
  image:
    tag: "3.0.1"
  replicaCount: 7
database:
  image:
    tag: "16"
  replicaCount: 4
redis:
  profile: stateful
  image:
    tag: "7.4.1"
  replicaCount: 3