# Tag/replica + env. useExternalSecrets mặc định true trong template/values.yaml.
# helm ... -f app/be.yaml|db.yaml -f env/staging.yaml

env: staging

backend:
  image:
    tag: "3.0.1"
  replicaCount: 6
database:
  image:
    tag: "16"
  replicaCount: 4
