apiVersion: v1
kind: Secret
metadata:
  name: cluster-prod
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: prod
  server: https://10.2.101.84:6443
  config: |
    {
      "tlsClientConfig": {
        "insecure": true
      }
    }
